// const d = [...new Set(["pamela", "zoe", "pamela", "manuel"])]
// console.log(d)
const getUnique = async (arrayObject) => {
	return await [...new Set(arrayObject)]
}

exports.getUnique = getUnique

const arr = [
	"https://github.com/jlevy",
	"https://github.com/jlevy",
	"https://github.com/jlevy",
	"https://www.holloway.com",
	"https://airtable.com/shrzMhx00YiIVAWJg",
	"http://explainshell.com/",
	"http://superuser.com/a/183980/7106",
	"https://www.tldp.org/LDP/abs/html/here-docs.html",
	"https://tmux.github.io/",
	"https://github.com/bogner/dtach",
	"https://mosh.mit.edu/",
	"https://github.com/mooz/percol",
	"https://github.com/junegunn/fzf",
	"https://github.com/facebook/PathPicker",
	"https://wiki.debian.org/CommonErrorMessages/ArgumentListTooLong",
	"https://github.com/beyondgrep/ack2",
	"https://github.com/ggreer/the_silver_searcher",
	"https://github.com/BurntSushi/ripgrep",
	"http://pandoc.org/",
	"http://stedolan.github.io/jq/",
	"https://github.com/simeji/jid",
	"https://github.com/fiatjaf/jiq",
	"https://github.com/0k/shyaml",
	"https://github.com/onyxfish/csvkit",
	"https://github.com/s3tools/s3cmd",
	"https://github.com/bloomreach/s4cmd",
	"https://github.com/aws/aws-cli",
	"https://github.com/donnemartin/saws",
	"https://www.gnu.org/software/datamash/",
	"https://github.com/jlevy/repren",
	"https://web.archive.org/web/20130929001850/http://linuxnote.net/jianingy/en/linux/a-fast-way-to-remove-huge-number-of-files.html",
	"http://www.ivarch.com/programs/pv.shtml",
	"https://github.com/dmerejkowsky/pycp",
	"https://github.com/dspinellis/pmonitor",
	"https://github.com/Xfennec/progress",
	"https://en.wikipedia.org/wiki/ISO_8601",
	"https://stackoverflow.com/questions/7216358/date-command-on-os-x-doesnt-have-iso-8601-i-option",
	"https://unix.stackexchange.com/questions/164826/date-command-iso-8601-option",
	"http://www.fresse.org/dateutils/",
	"https://en.wikipedia.org/wiki/Sparse_file",
	"https://github.com/jkbrzt/httpie",
	"https://github.com/nicolargo/glances",
	"https://github.com/aragozin/jvm-tools",
	"http://www.bitwizard.nl/mtr/",
	"https://dev.yorhel.nl/ncdu",
	"http://www.ex-parrot.com/~pdw/iftop/",
	"https://github.com/raboof/nethogs",
	"https://wireshark.org/",
	"https://www.wireshark.org/docs/wsug_html_chunked/AppToolstshark.html",
	"http://ngrep.sourceforge.net/",
	"http://www.catonmat.net/blog/ldd-arbitrary-code-execution/",
	"http://sebastien.godard.pagesperso-orange.fr/",
	"https://sourceware.org/systemtap/wiki",
	"https://en.wikipedia.org/wiki/Perf_%28Linux%29",
	"https://github.com/draios/sysdig",
	"https://gnupg.org/",
	"https://github.com/mattthias/slurm",
	"https://github.com/joh/when-changed",
	"https://github.com/wg/wrk",
	"http://www.bitwizard.nl/mtr/",
	"https://wireshark.org/",
	"https://www.wireshark.org/docs/wsug_html_chunked/AppToolstshark.html",
	"http://ngrep.sourceforge.net/",
	"https://github.com/nicolargo/glances",
	"http://sebastien.godard.pagesperso-orange.fr/",
	"http://www.ex-parrot.com/~pdw/iftop/",
	"https://github.com/raboof/nethogs",
	"https://cygwin.com/",
	"https://msdn.microsoft.com/commandline/wsl/about",
	"http://www.mingw.org/",
	"http://www.mingw.org/wiki/msys",
	"https://github.com/dthree/cash",
	"http://www.thewindowsclub.com/rundll32-shortcut-commands-windows",
	"https://github.com/alebcay/awesome-shell",
	"https://github.com/herrbischoff/awesome-osx-command-line",
	"http://redsymbol.net/articles/unofficial-bash-strict-mode/",
	"https://github.com/koalaman/shellcheck",
	"http://www.dwheeler.com/essays/filenames-in-shell.html",
	"https://i.creativecommons.org/l/by-sa/4.0/88x31.png",
	"http://creativecommons.org/licenses/by-sa/4.0/",
]

// getUnique(arr)
// 	.then((data) => console.log(data))
// 	.catch((err) => console.log(err))
